students,addition_correct_average_time,addition_correct_average_memory,addition_total_test,addition_correct_output,addition_wrong_case_details,addition_pass_percent
PCS 9 - Mr.Timeout,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.time_limit_exceeded: 2>, time_used=-1, memory_used=50.39453125, expected=None, actual=None, err_message=""'Timed Out'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 99, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 90, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 172, in file_syle_case_handler\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Mr.Timeout/addition.py"", line 2, in add\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 69, in handler\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 45, in _raise_exception\ntimeout_decorator.timeout_decorator.TimeoutError: \'Timed Out\'\n'), TestCase.TestResult(result_type=<TestResultType.time_limit_exceeded: 2>, time_used=-1, memory_used=50.3984375, expected=None, actual=None, err_message=""'Timed Out'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 99, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 90, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./testcase/addition.py"", line 8, in test_rand_add\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Mr.Timeout/addition.py"", line 2, in add\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 69, in handler\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 45, in _raise_exception\ntimeout_decorator.timeout_decorator.TimeoutError: \'Timed Out\'\n')]",0.0
PCS 9 - No Homework,-1.0,-1.0,1,0,"[TestCase.TestResult(result_type=<TestResultType.solution_not_found: 7>, time_used=-1, memory_used=-1, expected=None, actual=None, err_message=None, stack_trace=None)]",0.0
PCS 9 - Dangerous Behavior,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.runtime_error: 5>, time_used=-1, memory_used=50.34375, expected=None, actual=None, err_message=""[Errno 13] Permission denied: '/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 99, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 90, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 172, in file_syle_case_handler\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/addition.py"", line 4, in add\nPermissionError: [Errno 13] Permission denied: \'/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt\'\n'), TestCase.TestResult(result_type=<TestResultType.runtime_error: 5>, time_used=-1, memory_used=50.3515625, expected=None, actual=None, err_message=""[Errno 13] Permission denied: '/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 99, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 90, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./testcase/addition.py"", line 8, in test_rand_add\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/addition.py"", line 4, in add\nPermissionError: [Errno 13] Permission denied: \'/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt\'\n')]",0.0
PCS 9 - Right Answer,0.1519918441772461,49.81640625,2,2,[],100.0
PCS 9 - Ms.Memout,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.memory_limit_exceeded: 3>, time_used=553.5843372344971, memory_used=512.78515625, expected=None, actual=None, err_message=None, stack_trace=None), TestCase.TestResult(result_type=<TestResultType.memory_limit_exceeded: 3>, time_used=518.4433460235596, memory_used=512.7890625, expected=None, actual=None, err_message=None, stack_trace=None)]",0.0
PCS 9 - Wrong Answer,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.wrong_answer: 1>, time_used=0.13709068298339844, memory_used=49.80078125, expected=3, actual=-1144, err_message=None, stack_trace=None), TestCase.TestResult(result_type=<TestResultType.wrong_answer: 1>, time_used=0.14209747314453125, memory_used=49.75, expected=46, actual=-1144, err_message=None, stack_trace=None)]",0.0
