students,addition_correct_average_time,addition_correct_average_memory,addition_total_test,addition_correct_output,addition_wrong_case_details,addition_pass_percent
PCS 9 - Ms.Memout,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.memory_limit_exceeded: 3>, time_used=587.0552062988281, memory_used=513.09765625, expected=None, actual=None, err_message=None, stack_trace=None, test_case_id=0), TestCase.TestResult(result_type=<TestResultType.memory_limit_exceeded: 3>, time_used=511.87944412231445, memory_used=513.1015625, expected=None, actual=None, err_message=None, stack_trace=None, test_case_id=1)]",0.0
PCS 9 - No Homework,-1.0,-1.0,1,0,"[TestCase.TestResult(result_type=<TestResultType.solution_not_found: 7>, time_used=-1, memory_used=-1, expected=None, actual=None, err_message=None, stack_trace=None, test_case_id=-1)]",0.0
PCS 9 - Right Answer,0.1455545425415039,49.849609375,2,2,[],100.0
PCS 9 - Mr.Timeout,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.time_limit_exceeded: 2>, time_used=-1, memory_used=50.3671875, expected=None, actual=None, err_message=""'Timed Out'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 100, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 91, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 173, in file_syle_case_handler\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Mr.Timeout/addition.py"", line 2, in add\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 69, in handler\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 45, in _raise_exception\ntimeout_decorator.timeout_decorator.TimeoutError: \'Timed Out\'\n', test_case_id=0), TestCase.TestResult(result_type=<TestResultType.time_limit_exceeded: 2>, time_used=-1, memory_used=50.37109375, expected=None, actual=None, err_message=""'Timed Out'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 100, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 91, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./testcase/addition.py"", line 8, in test_rand_add\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Mr.Timeout/addition.py"", line 2, in add\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 69, in handler\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 45, in _raise_exception\ntimeout_decorator.timeout_decorator.TimeoutError: \'Timed Out\'\n', test_case_id=1)]",0.0
PCS 9 - Wrong Answer,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.wrong_answer: 1>, time_used=0.12183189392089844, memory_used=49.75, expected=3, actual=-1144, err_message=None, stack_trace=None, test_case_id=0), TestCase.TestResult(result_type=<TestResultType.wrong_answer: 1>, time_used=0.1685619354248047, memory_used=49.84375, expected=102, actual=-1144, err_message=None, stack_trace=None, test_case_id=1)]",0.0
PCS 9 - Dangerous Behavior,-1.0,-1.0,2,0,"[TestCase.TestResult(result_type=<TestResultType.runtime_error: 5>, time_used=-1, memory_used=50.31640625, expected=None, actual=None, err_message=""[Errno 13] Permission denied: '/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 100, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 91, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 173, in file_syle_case_handler\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/addition.py"", line 4, in add\nPermissionError: [Errno 13] Permission denied: \'/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt\'\n', test_case_id=0), TestCase.TestResult(result_type=<TestResultType.runtime_error: 5>, time_used=-1, memory_used=50.16796875, expected=None, actual=None, err_message=""[Errno 13] Permission denied: '/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt'"", stack_trace='Traceback (most recent call last):\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 100, in proc_task\n  File ""/mnt/e/cling/miniconda/lib/python3.11/site-packages/timeout_decorator/timeout_decorator.py"", line 82, in new_function\n  File ""/mnt/e/prog/python/PyAutoGrade/./src/test_case.py"", line 91, in get_test_ret\n  File ""/mnt/e/prog/python/PyAutoGrade/./testcase/addition.py"", line 8, in test_rand_add\n  File ""/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/addition.py"", line 4, in add\nPermissionError: [Errno 13] Permission denied: \'/mnt/e/prog/python/PyAutoGrade/./test_input/PCS 9 - Dangerous Behavior/test.txt\'\n', test_case_id=1)]",0.0
